const FETCH_CONTACTS = "FETCH_CONTACTS";
const ADD_CONTACT = "ADD_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";
const EDIT_CONTACT = "EDIT_CONTACT";
const SHOW_ERROR = "SHOW_ERROR";
const HIDE_ERROR = "HIDE_ERROR";

export {
    FETCH_CONTACTS,
    ADD_CONTACT,
    DELETE_CONTACT,
    EDIT_CONTACT,
    SHOW_ERROR,
    HIDE_ERROR
}