const FETCH_CONTACTS = "FETCH_CONTACTS";
const ADD_CONTACT = "ADD_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";
const UPDATE_CONTACT = "UPDATE_CONTACT";
const EDIT_CONTACT = "EDIT_CONTACT";
const SHOW_ERROR = "SHOW_ERROR";
const HIDE_ERROR = "HIDE_ERROR";
const CLEAR_STORE = "CLEAR_STORE";

export {
    FETCH_CONTACTS,
    ADD_CONTACT,
    DELETE_CONTACT,
    UPDATE_CONTACT,
    EDIT_CONTACT,
    SHOW_ERROR,
    HIDE_ERROR,
    CLEAR_STORE
}